### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ebullienc3** [TuringAI-Team/chatgpt-discord-bot#23]
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.

D:\Bots\chatgpt-discord-bot-main>npm start

> chatgpt-bot@0.3.3 start
> tsc && node .

[Top.gg Votes] Vote client is running on port 39762
Launched shard 0
[Top.gg Votes] Vote client is running on port 17670
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'D:\Bots\chatgpt-discord-bot-main\previousCommands\1.json'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at commandHandler (file:///D:/Bots/chatgpt-discord-bot-main/dist/handlers/commands.js:39:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Bots\\chatgpt-discord-bot-main\\previousCommands\\1.json'
}

Node.js v18.15.0
[Top.gg Votes] Vote client is running on port 54806
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'D:\Bots\chatgpt-discord-bot-main\previousCommands\1.json'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at commandHandler (file:///D:/Bots/chatgpt-discord-bot-main/dist/handlers/commands.js:39:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Bots\\chatgpt-discord-bot-main\\previousCommands\\1.json'
}

Node.js v18.15.0
D:\Bots\chatgpt-discord-bot-main\node_modules\discord.js\src\sharding\Shard.js:171
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^

Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (D:\Bots\chatgpt-discord-bot-main\node_modules\discord.js\src\sharding\Shard.js:171:16)
    at Object.onceWrapper (node:events:628:26)
    at Shard.emit (node:events:513:28)
    at Shard._handleExit (D:\Bots\chatgpt-discord-bot-main\node_modules\discord.js\src\sharding\Shard.js:421:10)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on Shard instance at:
    at D:\Bots\chatgpt-discord-bot-main\node_modules\discord.js\src\sharding\Shard.js:429:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ShardingReadyDied'
}

Node.js v18.15.0

D:\Bots\chatgpt-discord-bot-main>

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
